/**
 * Generated by tsnapi — public API snapshot of `vite-plugin-define-types-dts` */
// Interfaces
export interface DefineTypesPluginOptions {
  apply?: Plugin['apply'];
  excludeKeys?: string[];
  outputPath?: string;
  strictDefineKey?: boolean;
}

// Functions
export declare function defineTypesPlugin(_?: DefineTypesPluginOptions): Plugin;