/**
 * Generated by tsnapi — public API snapshot of `vite-plugin-define-types-dts` */
// Interfaces
export interface DefineTypesPluginOptions {
  apply?: 'serve' | 'build';
  outputPath?: string;
}

// Functions
export declare function defineTypesPlugin(_?: DefineTypesPluginOptions): Plugin;