import type { Plugin } from 'vite'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const DEFINE_KEY_RE = /^__[A-Z0-9_]+__$/

function inferTsType(value: unknown): string {
  if (value === null)
    return 'null'

  if (Array.isArray(value))
    return 'unknown[]'

  switch (typeof value) {
    case 'boolean':
    case 'number':
    case 'string':
      return typeof value
    case 'object':
      return 'Record<string, unknown>'
    default:
      return 'unknown'
  }
}

function inferDefineType(value: unknown): string {
  if (typeof value !== 'string')
    return inferTsType(value)

  try {
    return inferTsType(JSON.parse(value))
  }
  catch {
    return 'unknown'
  }
}

export function defineTypesPlugin(outputPath = 'src/define-types.d.ts'): Plugin {
  return {
    name: 'define-types',
    configResolved(config) {
      const defines = config.define ?? {}
      const invalidKeys: string[] = []
      const lines = Object.entries(defines)
        .sort(([a], [b]) => a.localeCompare(b))
        .flatMap(([key, value]) => {
          if (!DEFINE_KEY_RE.test(key)) {
            invalidKeys.push(key)
            return []
          }
          return [`declare const ${key}: ${inferDefineType(value)}`]
        })

      if (invalidKeys.length > 0) {
        config.logger.warn(
          `[define-types] Skipped ${invalidKeys.length} define key(s) that do not match ${DEFINE_KEY_RE}: ${invalidKeys.join(', ')}`,
        )
      }

      const content = [
        '// Auto-generated by defineTypesPlugin — do not edit',
        ...lines,
        '',
      ].join('\n')
      const outputFile = resolve(config.root, outputPath)

      mkdirSync(dirname(outputFile), { recursive: true })

      let previousContent = ''
      try {
        previousContent = readFileSync(outputFile, 'utf8')
      }
      catch {
        // Ignore read errors and write the file below.
      }

      if (previousContent !== content)
        writeFileSync(outputFile, content, 'utf8')
    },
  }
}
